### ISSUE TITLE
Lower cmake to 3.10?

### ISSUE THREAD

**Issue by versatran01** [kmhofmann/selene#10]
Is it possible to lower cmake requirement to 3.10? Which is default on ubuntu 18.04?

**Comment by kmhofmann** [comment]
Hi @versatran01, thanks for reporting!
I'm afraid this is not possible without uglifying the CMakeLists.txt code and regressing to inconsistent dependency handling. I had deliberately increased the minimum required CMake version in https://github.com/kmhofmann/selene/commit/172249e11bcdb93909689a4295e2b54fd88d64ba, in order to be able to use imported targets throughout (a CMake best practice).

Unfortunately, Ubuntu LTS releases are very bad offenders at not updating their packages in a timely or proper manner. Other Linux distributions (e.g. Arch) or package managers (e.g. Homebrew on macOS) do not suffer from this problem. Therefore I consider this to be more of an Ubuntu issue than a Selene issue.

The good news is that it is easy to download and install up-to-date CMake versions, so I do not see a good reason to be compatible with a very outdated CMake version, which I consider v3.10 to be.

To download the official CMake binary and put it on the PATH on a user level (e.g. to `$HOME/local`), you can execute something like the following Bash snippet:

    dst=$HOME/local \
    && cmake_ver="3.15.2" \
    && mkdir -p ${dst} \
    && wget -O - -o /dev/null https://github.com/Kitware/CMake/releases/download/v${cmake_ver}/cmake-${cmake_ver}-Linux-x86_64.tar.gz \
       | tar zxf - -C ${dst} \
    && export PATH=${dst}/cmake-${cmake_ver}-Linux-x86_64/bin:$PATH

Alternatively, you can compile CMake from source, see https://gitlab.kitware.com/cmake/cmake. It's also fairly straightforward, and decent instructions are provided.
I am also providing a helper script [here](https://github.com/kmhofmann/build_stuff/blob/master/build_cmake.sh) that further simplifies this process. For example, you could call it as such:

    ./build_cmake.sh -s /tmp -t $HOME/local/cmake

or, to specify a particular version:

    ./build_cmake.sh -s /tmp -t $HOME/local/cmake-3.15.2 -T v3.15.2

(At the time of writing, CMake v3.15.2 was the latest release. Of course this should be updated as new versions get released; see [here](https://gitlab.kitware.com/cmake/cmake/-/tags).)

**Comment by versatran01** [comment]
Thanks for a detailed reply.
It looks like libjpeg is the only problem here.
Perhaps something like this to handle libjpeg?
https://pabloariasal.github.io/2018/02/19/its-time-to-do-cmake-right/#if-you-want-it-done-right-do-it-yourself

**Comment by kmhofmann** [comment]
I do not think this is a good idea, since CMake versions 3.12 and up offer direct support for this library as an imported target.
In theory, it would be much easier to revert to the `target_include_directories` and `target_link_libraries` calls prior to https://github.com/kmhofmann/selene/commit/172249e11bcdb93909689a4295e2b54fd88d64ba, but again, I don't think this is the right solution.

I can primarily advise to use a more recent CMake version.
